language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t JReich/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true JReich/docker-react npm run test
